# Generated by Django 6.0.5 on 2026-05-16 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('number_of_arrows', models.PositiveIntegerField()),
                ('maximum_score', models.PositiveIntegerField()),
                ('system', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shot', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('bow_type', models.CharField(choices=[('Recurve', 'Recurve'), ('Compound', 'Compound'), ('Barebow', 'Barebow'), ('Longbow', 'Longbow'), ('Other', 'Other')], max_length=20)),
                ('score', models.PositiveIntegerField()),
                ('witness', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_personal_best', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scores.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_shot'],
            },
        ),
    ]
