# Generated by Django 6.0.5 on 2026-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined_club',
            field=models.DateField(blank=True, null=True, verbose_name='Original date of joining'),
        ),
    ]
