# Generated by Django 6.0.5 on 2026-05-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course fee in GBP (0 = free)', max_digits=8),
        ),
    ]
