# Generated by Django 6.0.5 on 2026-05-17 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='acceptance_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='acceptance_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='details_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='eye_dominance',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both / Central'), ('unknown', 'Not sure')], max_length=10),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='handedness',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='strength',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('waitlist', 'On Waitlist'), ('accepted', 'Accepted — Awaiting Details'), ('details', 'Details Submitted — Awaiting Payment'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
    ]
